### ISSUE TITLE
Rarible Indexer

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#187]
Hello,
yesterday we recognized some issue with your indexer:
- This collection (Divine Anarchy) is missing: 0xc631164B6CB1340B5123c9162f8558c866dE1926 ;

Plus:
This users own 4 Ether-Orcs
https://opensea.io/SA1NT_eth/ether-orcs?search[sortBy]=LISTING_DATE

But the indexer send me back 3 Ether-Orcs and those are different.
Using this endpoint: https://ethereum-api.rarible.org/v0.1/nft/items/byOwner?owner=0x0e95ee3a584d95ce952f31b042ac0d5237644431&includeMeta=false 

Could you check? Thanks

**Comment by eduardstal** [comment]
It appears the collection is not indexed: https://ethereum-api.rarible.org/v0.1/nft/collections/0xc631164B6CB1340B5123c9162f8558c866dE1926. @sanufriev @evgenynacu 

I've seen something similar where a collection wasn't indexed (I think it was roaring leaders), I went to bed and checked it in the morning again, and at that time it was showing up. Maybe there's some delay with the indexer? 

About Ether-Orcs, we'll look into it.

**Comment by bruck93** [comment]
Let me add that also this collection is not well indexed: https://opensea.io/collection/doodles-official
We said to refresh metadata and so on, but nothing.

**Comment by bruck93** [comment]
The issue is still available, other used reached us

**Comment by LoBoTheSpaceHoBo** [comment]
Hello I am reaching out from the Rug.Tech team. We have numerous projects not properly shown at this moment. Below I will share the links in order of importance.

[https://rarible.com/collection/0x8584e7a1817c795f74ce985a1d13b962758fe3ca](url) (Blazed Cats)
[https://rarible.com/collection/0x6c94954d0b265f657a4a1b35dfaa8b73d1a3f199](url) (Rug.WTF)
[https://rarible.com/collection/0x5e9dc633830af18aa43ddb7b042646aadedcce81](url) (DOJICREW)
[https://rarible.com/collection/0x4a8b01e437c65fa8612e8b699266c0e0a98ff65c](url) (Space Poggers)

These are just four of the many projects we have not displayed correctly. These projects are the most important because we have introduced something we created called "Quantum Metadata" to the NFTs. This gives the user the ability to see special traits and info through Rarible, Opensea etc. See example [https://opensea.io/assets/0x8584e7a1817c795f74ce985a1d13b962758fe3ca/4112](url) Notice the Opensea preview of my NFT shows a few of the features not already available on the opensea platform. 

We hope we can get this figured out as soon as possible please contact me if you have any questions

-@Specialist.L@rug.marketing

**Comment by evgenynacu** [comment]
Hey
@SpecialistLoBo what kind of Quantum Metadata are you talking about?
I check it here: https://blazedcats.s3.us-east-2.amazonaws.com/metadata/3.0.0/4112

How should it work?

**Comment by SpecialistLoBo** [comment]
Is there a way I could get you in a meeting with the dev team? I am not the
most equipped person for this conversation. This is a priority issue for us.

**Comment by eduardstal** [comment]
> Is there a way I could get you in a meeting with the dev team? I am not the most equipped person for this conversation. This is a priority issue for us.
> […](#)

You could ask them to reply to this GitHub issue instead. @SpecialistLoBo

**Comment by bruck93** [comment]
Any updates on this ?

**Comment by eduardstal** [comment]
> Any updates on this ?

The last update I had on it was that it's currently being looked into. The team has discovered some more collections with similar issues so they're fixing all of them.

**Comment by evgenynacu** [comment]
Closing this as it seems fixed
Feel free to reopen if there are such problems
