### ISSUE TITLE
Polygon not working for certain calls

### ISSUE THREAD

**Issue by mvanhalen** [rarible/protocol#423]
Some calls which claim to have Polygon support now return:

`{
    "code": "BAD_REQUEST",
    "message": "Unsupported blockchain group value: POLYGON, supported are: ETHEREUM|FLOW|TEZOS|SOLANA"
}`

This happens with https://api.rarible.org/v0.1/items/byOwner or https://api.rarible.org/v0.1/items/byCreator

Please check. Thanks

**Comment by iskurenkov** [comment]
Good day @mvanhalen,

Probably when you enter a user address you use the prefix `POLYGON`, in order to find items created by the user you need to select the parameter `blockchains: POLYGON` and owner specify `ETHEREUM:$address`, then you will find all items owned or created by the address. This is because in EVM networks the address of one user is the same, so you should specify `ETHEREUM:$address`.

Here is an example of a valid query that will return all items that the user has created on Polygon:
`curl --location 'https://api.rarible.org/v0.1/items/byCreator?blockchains=POLYGON&creator=ETHEREUM%3A0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270&size=5'`

Don't forget to use your API-Key 🙌

**Comment by mvanhalen** [comment]
> Good day @mvanhalen,
> 
> Probably when you enter a user address you use the prefix `POLYGON`, in order to find items created by the user you need to select the parameter `blockchains: POLYGON` and owner specify `ETHEREUM:$address`, then you will find all items owned or created by the address. This is because in EVM networks the address of one user is the same, so you should specify `ETHEREUM:$address`.
> 
> Here is an example of a valid query that will return all items that the user has created on Polygon: `curl --location 'https://api.rarible.org/v0.1/items/byCreator?blockchains=POLYGON&creator=ETHEREUM%3A0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270&size=5'`
> 
> Don't forget to use your API-Key 🙌

Thanks that was it indeed. Kinda weird error though. It´s working now.
